name: synchronized_lite
description: A locking mechanism for Dart analogous to synchronized blocks in Java.
version: 1.1.0
authors:
  - Alexander Ryzhov <aryzhov07@gmail.com>
  - azulli
homepage: https://github.com/azulli/synchronized_lite

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test:
  synchronized:
